<?php

declare(strict_types=1);

namespace Tests\Support;

use RuntimeException;

/**
 * Locates the committed test fixtures.
 *
 * The .nupkg files come from `dotnet pack` and the version oracle from
 * NuGet.Versioning; both are regenerated by the scripts in tools/ and then
 * committed, so the suite runs without the .NET SDK.
 */
final class Fixtures
{
    public static function path(string $relative = ''): string
    {
        return __DIR__ . '/Fixtures/' . ltrim($relative, '/');
    }

    /**
     * Absolute path to a fixture package, by file name.
     */
    public static function package(string $fileName): string
    {
        $path = self::path('Packages/' . $fileName);

        if (! is_file($path)) {
            throw new RuntimeException(sprintf(
                'Missing fixture package "%s". Run tools/build-fixtures.sh.',
                $fileName,
            ));
        }

        return $path;
    }

    public static function contents(string $relative): string
    {
        $path = self::path($relative);

        if (! is_file($path)) {
            throw new RuntimeException(sprintf('Missing fixture "%s".', $relative));
        }

        return file_get_contents($path);
    }

    /**
     * @return list<mixed>
     */
    public static function json(string $relative): array
    {
        return json_decode(self::contents($relative), true, 512, JSON_THROW_ON_ERROR);
    }
}
